### ISSUE TITLE
Wrong Refs

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Qualification-DDI-CYP1A2#3]
Wrong refs in https://github.com/Open-Systems-Pharmacology/Qualification-DDI-CYP1A2/blob/main/Qualification/Input/Content/Qualification_objective.md:

Expected: 12-cyp1a2-ddi-network
Currentl:   12-CYP2C19-DDI-Network

Expected: 61-open-systems-pharmacology-suite-osps-introduction
Currentl:   61-Open-Systems-Pharmacology-Suite-(OSPS)-Introduction

Expected: 63-automatic-re-qualification-workflow
Currentl:   63-Automatic-(re)-qualification-workflow

**Comment by PavelBal** [comment]
Should I create a new release or just delete the old one and replace it?

**Comment by Yuri05** [comment]
I would replace

**Comment by PavelBal** [comment]
Fixed
